# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: /:title/
excerpt_separator: ""

# Setup
title:            Landswellsong
url:              http://landswellsong.github.io
t:
    en:
      tagline:          'blog by Oleksiy Protas'
      description:      'Pretty nerdy stuff is being written here. Bioinformatics, computational politics and 
mathematical journalism — no one will leave without confusion!'
      indexurl:         '/en'
      githubtxt:        'This site on GitHub'
      themetxt:         'Jekyll theme'
      copylefttxt:      'All wrongs liberated.'
      licensetext:      'Since we still live in an imperfect world, the content of the blog is protected by '
    uk:
      tagline:          'блоґ Олексія Протаса'
      description:      'Тут пишуть про всілякі заумні гадості. Біоінформатика, обрахункова політика й математичний 
журналізм — ніхто не лишиться незаплутаним!'
      indexurl:         '/'
      githubtxt:        'Цей сайт на GitHub'
      themetxt:         'Тема для Jekyll'
      copylefttxt:      'Усі ліва звільнено.'
      licensetext:      'Оскільки ми досі живемо у недосконалому світі, матеріали цього блоґу захищено ліцензією '

author:
  name:           'Oleksiy Protas'
  facebook:       https://www.facebook.com/protas.oleksiy
  twitter:        https://twitter.com/Landswellsong
  linkedin:       https://www.linkedin.com/pub/oleksiy-protas/34/863/454 
  vk:             https://vk.com/landswellsong
  github:         https://github.com/landswellsong

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/landswellsong/landswellsong.github.io
  theme:          https://github.com/poole/lanyon


# Multiple languages (thanks to https://sylvain.durand.tf/making-jekyll-multilingual/)
defaults:
  -
    values:
      layout: 'default'
      lang: 'uk'
  -
    scope:
      path: '_posts/en'
    values:
      lang: 'en'
  -
    scope:
      path: 'en'
    values:
      lang: 'en'

      
