# Dependencies
# TODO: GitHub is moving to kramdown/rouge, update it, also check sylvain's typography hack
# Source: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
markdown:         kramdown
highlighter:      pygments

gems:
  - jekyll-mentions

# Permalinks
permalink: /:categories/:title/
excerpt_separator: ""

# Setup
title:            Landswellsong
url:              http://landswellsong.github.io
t:
    en:
      inverse:          'uk'
      tagline:          'blog by Oleksiy Protas'
      description:      'Pretty nerdy stuff is being written here. Bioinformatics, computational politics and
mathematical journalism — no one will leave without confusion!'
      indexurl:         '/en'
      keytxt:           'key'
      githubtxt:        'This site on GitHub'
      themetxt:         'Jekyll theme'
      copylefttxt:      'All wrongs liberated.'
      licensetext:      'Since we still live in an imperfect world, the content of the blog is protected by '
      languagetoggle:   'Українська версія'
      warning:          'WARNING:'
      gawarning:        'This site uses Google Analytics'
      atomtitle:        'ATOM news feed'
      figurelabel:      'Fig'
    uk:
      inverse:          'en'
      tagline:          'бліґ Олексія Протаса'
      description:      'Тут пишуть про всілякі заумні гадості. Біоінформатика, обрахункова політика й математичний
журналізм — ніхто не лишиться незаплутаним!'
      indexurl:         '/'
      keytxt:           'ключ'
      githubtxt:        'Цей сайт на GitHub'
      themetxt:         'Тема для Jekyll'
      copylefttxt:      'Усі ліва звільнено.'
      licensetext:      'Оскільки ми досі живемо у недосконалому світі, матеріали цього блоґу захищено ліцензією '
      languagetoggle:   'English version'
      warning:          'УВАГА:'
      gawarning:        'Сайт використовує Google Analytics'
      atomtitle:        'Стрічка новин в форматі ATOM'
      figurelabel:      'Рис'

author:
  name:           'Oleksiy Protas'
  facebook:       https://www.facebook.com/protas.oleksiy
  twitter:        https://twitter.com/Landswellsong
  linkedin:       https://www.linkedin.com/pub/oleksiy-protas/34/863/454
  vk:             https://vk.com/landswellsong
  github:         https://github.com/landswellsong
  pgpkey:         https://gist.githubusercontent.com/landswellsong/3051b162e887f96f9645/raw/a1da270331e9d7dbbe76a52d8d5e2f000338b83f/landswellsong_pub.gpg

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/landswellsong/landswellsong.github.io
  theme:          https://github.com/poole/lanyon


# Multiple languages (thanks to https://sylvain.durand.tf/making-jekyll-multilingual/)
# TODO: this requires update for Jekyll 3
# Also: https://github.com/sylvaindurand/sylvaindurand.org/issues/4
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: '_posts/en'
    values:
      lang: en
      category: en
  -
    scope:
      path: '_drafts/en'
    values:
      lang: en
      category: en
  -
    scope:
      path: '_posts/uk'
    values:
      lang: uk
      category: uk
  -
    scope:
      path: '_drafts/uk'
    values:
      lang: uk
      category: uk
  -
    scope:
      path: ''
    values:
      lang: uk
  -
    scope:
      path: en
    values:
      lang: en
