# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty
excerpt_separator: ""

# Setup
title:            Landswellsong
url:              http://landswellsong.github.io
t:
    en:
      tagline:          'blog by Oleksiy Protas'
      description:      'Pretty nerdy stuff is being written here. Bioinformatics, computational politics and 
mathematical journalism — no one will leave without confusion!'
      indexurl:         '/index.html'
      oldertxt:         '← Older'
      newertxt:         'Newer →'
      githubtxt:        'This site on GitHub'
      themetxt:         'Jekyll theme'
      copylefttxt:      'All wrongs liberated.'
    uk:
      tagline:          'блоґ Олексія Протаса'
      description:      'Тут пишуть про всілякі заумні гадості. Біоінформатика, обрахункова політика й математичний 
журналізм — ніхто не лишиться незаплутаним!'
      indexurl:         '/poczatok.html'
      oldertxt:         '← Старіші'
      newertxt:         'Новіші →'
      githubtxt:        'Цей сайт на GitHub'
      themetxt:         'Тема для Jekyll'
      copylefttxt:      'Усі ліва звільнено.'

author:
  name:           'Oleksiy Protas'
  facebook:       https://www.facebook.com/protas.oleksiy
  twitter:        https://twitter.com/Landswellsong
  linkedin:       https://www.linkedin.com/pub/oleksiy-protas/34/863/454 
  vk:             https://vk.com/landswellsong
  github:         https://github.com/landswellsong

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/landswellsong/landswellsong.github.io
  theme:          https://github.com/poole/lanyon


# Multiple languages (thanks to https://sylvain.durand.tf/making-jekyll-multilingual/)
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/uk
    values:
      layout: default
      lang: uk
  -
    scope:
      #path: index.html
      path: ""
    values:
      layout: default
      lang: en
  -
    scope:
      path: poczatok.html
    values:
      layout: default
      lang: uk
